name: apple_avtopoisk1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  confirm_dialog: ^1.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



